### ISSUE TITLE
Opening fooxfooding form for Nightly foxfooding event

### ISSUE THREAD

**Issue by couci** [mozilla/campaign-form#10]
The foxfooding form needs to open for the upcoming Foxfooding Nightly event

Repo it will open issues to: https://github.com/mozilla/Foxfooding_Firefox_Nightly_2022
Picture on top: Nightly logo
Extra fields needed: OS - we need to understand if the bug occurs on desktop (and if so what OS) Android or iPhone. If this is not detectable let's have it as a drop down

**Comment by MichaelKohler** [comment]
Now ready at https://foxfooding-form.mozilla.community/

Example issue: https://github.com/mozilla/Foxfooding_Firefox_Nightly_2022/issues/4 (please delete once reviewed)
