### ISSUE TITLE
TODOs for the next campaign

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/campaign-form#5]
- [x] Get Title
- [x] Get Logo
- [x] Invite bot to private issue repo (@couci)
- [x] Set up environment variables to point to the correct repository
- [x] Anything else?

**Comment by MichaelKohler** [comment]
@couci if you already have that info, you can also send it to me in a message if you can't post it here. Then I can prepare it without uploading it for now.

**Comment by couci** [comment]
We would also need the phone info. For the logo we can just use the nightly logo, title: foxfooding for Android and iOS

**Comment by MichaelKohler** [comment]
I've prepared this on my laptop, will push it on Monday.
